apiVersion: v1
kind: Pod
metadata:
  namespace: epbot
  name: epbot
  labels:
    app: epbot

spec:
  containers:
    - name: postgresql
      image: pikokr/epbot-origin-db
      volumeMounts:
        - mountPath: /var/lib/postgres/data
          name: db
    - name: bot
      image: pikokr/epbot-origin
      imagePullPolicy: Always
      envFrom:
        - configMapRef:
            name: epbot-config
  volumes:
    - name: db
      hostPath:
        path: /opt/epbot/data/db
        type: DirectoryOrCreate
