apiVersion: apps/v1
kind: Deployment

metadata:
  name: epbot
  namespace: epbot
  labels:
    app: epbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: epbot
  template:
    metadata:
      namespace: epbot
      name: epbot
      labels:
        app: epbot

    spec:
      containers:
        - name: postgresql
          image: pikokr/epbot-origin-db
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db
        - name: bot
          image: pikokr/epbot-origin
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: epbot-config
          env:
            - name: EP_DB_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
        - name: image-generator
          image: pikokr/epbot-origin-image-generator
          imagePullPolicy: Always
          env:
            - name: JWT_TOKEN
              valueFrom:
                configMapKeyRef:
                  key: EP_CARD_TOKEN
                  name: epbot-config
            - name: PORT
              value: '3001'
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: epbot-pg-data-claim