apiVersion: v1
kind: PersistentVolume

metadata:
  name: epbot-pg-data
  namespace: epbot

spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /opt/epbot/data/db
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - your-node-here
---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  namespace: epbot
  name: epbot-pg-data-claim

spec:
  storageClassName: ''
  volumeName: epbot-pg-data
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
